name: Yannis Orfanos
favicon: null
layout_spectrum: 0.8780363763216883
typography_spectrum: 0.91256
title: Yannis Orfanos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.11316233384422958
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
