name: Yannis Orfanos
favicon: null
layout_spectrum: 0.8780363763216883
typography_spectrum: 0.11640565376728773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.11316233384422958
  lightness: 0.7901507779024541
  saturation: 0.3670995570719242
  rhythmicContrast: 0.16455110744573176
purpose: []
