name: Yannis Orfanos
favicon: null
layout_spectrum: 0.68605
typography_spectrum: 0.91256
title: Yannis Orfanos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.375
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
